Oodle/Oodle/Models/Assignment.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Assignment")]
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            Documents = new HashSet<Document>();
            Grades = new HashSet<Grade>();
            Questions = new HashSet<Question>();
        }

        public int AssignmentID { get; set; }

        public int ClassID { get; set; }

        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        [StringLength(512)]
        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? DueDate { get; set; }

        public int Weight { get; set; }

        public virtual Class Class { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}

Oodle/Oodle/Models/Grade.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grade()
        {
            Documents = new HashSet<Document>();
            StudentQuizzes = new HashSet<StudentQuizze>();
        }

        public int GradeID { get; set; }

        [Column("Grade")]
        public int? Grade1 { get; set; }

        public int? AssignmentID { get; set; }

        public int ClassID { get; set; }

        public int? QuizID { get; set; }

        public int GradeWeight { get; set; }

        public DateTime DateApplied { get; set; }

        public virtual Assignment Assignment { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }

        public virtual Quizze Quizze { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentQuizze> StudentQuizzes { get; set; }
    }
}

Oodle/Oodle/Models/Tasks.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Tasks
    {
        [Key]
        public int TasksID { get; set; }

        public int ClassID { get; set; }

        [StringLength(512)]
        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? DueDate { get; set; }

        public virtual Class Class { get; set; }


        [StringLength(250)]
        public string Name { get; set; }

        [StringLength(250)]
        public string ContentType { get; set; }

        public byte[] Data { get; set; }

    }
}

Oodle/Oodle/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Oodle.Models;
using Oodle.Models.ViewModels;
using Oodle.Models.Repos;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Configuration;
using System.Diagnostics;
using Oodle.Utility;
using System.Text.RegularExpressions;

namespace Oodle.Controllers
{
    [Authorize]
    public class TeachersController : Controller 
    {
        //Slack access
        private SlackManager slack = new SlackManager();


        //Regular database
        //private Model1 db = new Model1();
        //Repo for mocking database
        private IOodleRepository db;

        public TeachersController(IOodleRepository repo)
        {
            this.db = repo;
        }

        public ActionResult test(int classID)
        {
            var idid = User.Identity.GetUserId();

            User user = db.Users.Where(a => a.IdentityID == idid).FirstOrDefault();
            UserRoleClass urc = db.UserRoleClasses.Where(s => s.UsersID == user.UsersID && s.ClassID == classID).FirstOrDefault();

            if (urc == null || urc.RoleID != 0)
            {
                return RedirectToAction("Index", "Class", new { classId = classID });
            }
            return null;
        }


        public ActionResult Index(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }
            var teacher = getTVM(classID);

            return View("index", "_TeacherLayout", teacher);
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexPost(int classID)
        {
            if (test(classID) != null)
            {

                return test(classID);
            }


            var teacher = getTVM(classID);
            var classes = db.Classes.ToList(); // list of all classes



            ViewBag.classList = classes;
            foreach (var item in classes) // Loop through List with foreach
            {
                System.Diagnostics.Debug.WriteLine(item);
            }


           System.Diagnostics.Debug.WriteLine(classes);


            ViewBag.RequestMethod = "POST";

            string desc = Request.Form["description"];
            string id = Request.Form["classID"];


            if (test(classID) != null)
            {
                return test(classID);
            }
            var note = new Notes();

            note.NotesID = db.Tasks.Count() + 1;
            note.Description = desc;
            note.ClassID = classID;


            db.AddNote(note);
            db.SaveChanges();


            teacher.Notes = db.Notes.ToList();

            return View("index", "_TeacherLayout", teacher);
        }







        public ActionResult Accept(int classID, int userID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            db.UserRoleClasses.Where(i => i.UsersID == userID & i.ClassID == classID).ToList().ForEach(x => x.RoleID = 2);
            db.SaveChanges();



            //get user and class
            User user = db.Users.Where(i => i.UsersID == userID).FirstOrDefault();
            Class c = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();
            //Send request to slack for user to join the group
            if (slack.HasToken() && !c.SlackName.Equals("%") && slack.IsOnSlack(user.Email))
            {
                slack.JoinChannel(user.Email, c.SlackName);
            }
            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult Reject(int classID, int userID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            db.RemoveURC(db.UserRoleClasses.Where(i => i.UsersID == userID & i.ClassID == classID).FirstOrDefault());
            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult Edit(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            ViewBag.id = classID;

            var teacher = getTVM(classID);

            return View("Edit", "_TeacherLayout", teacher);
        }

        public ActionResult EditClass()
        {
            ViewBag.RequestMethod = "POST";

            string name = Request.Form["name"];
            string desc = Request.Form["description"];
            int classID = int.Parse(Request.Form["classID"]);

            if (test(classID) != null)
            {
                return test(classID);
            }

            db.Classes.Where(i => i.ClassID == classID).ToList().ForEach(x => x.Name = name);
            db.Classes.Where(i => i.ClassID == classID).ToList().ForEach(x => x.Description = desc);

            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        /// <summary>
        /// Loads the add notification view
        /// </summary>
        /// <param name="classID">ID of Class</param>
        /// <returns>The Add Notification View</returns>
        public ActionResult AddNotifToClass(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            ViewBag.id = classID;

            var teacher = getTVM(classID);

            return View("AddNotifToClass", "_TeacherLayout", teacher);
        }

        /// <summary>
        /// Adds the slack notification to the database and slack
        /// </summary>
        /// <param name="notif">notification text</param>
        /// <param name="classID">ID of Class</param>
        /// <returns>true if added to database successfully, false if not</returns>
        public Boolean AddNotifToDB(string notif, int classID)
        {
            Boolean rtn = false;
            Class hasSlack = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();


            if (!(string.IsNullOrEmpty(notif)))
            {
                if (!hasSlack.SlackName.Equals("%"))
                {
                    slack.SlackNotif(notif, hasSlack.SlackName);
                }
                AddNotification(notif, classID);
                rtn = true;
            }
            return rtn;
        }

        /// <summary>
        /// Gets the Notification data from the view, and saves it in the database
        /// </summary>
        /// <returns>Index page of class</returns>
        public ActionResult SaveNotif()
        {
            ViewBag.RequestMethod = "POST";
            string notif = Request.Form["notification"];
            int classID = int.Parse(Request.Form["classID"]);

            AddNotifToDB(notif, classID);

            return RedirectToAction("Index", new { classId = classID });
        }

        /// <summary>
        /// Loads the Remove Notification View to verify removing Notification
        /// </summary>
        /// <param name="classID">ID of Class</param>
        /// <param name="notifID">ID of Notification</param>
        /// <returns>RemoveNotification View if successful, otherwise redirects to class index page</returns>
        public ActionResult RemoveNotif(int classID, int notifID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            ClassNotification cNotif = db.ClassNotifications.Where(n => n.ClassID == classID 
                                                                && n.ClassNotificationID == notifID).FirstOrDefault();
            if(cNotif == null)
            {
                return RedirectToAction("Index", new { classId = classID });
            }

            var teacher = getTVM(classID);
            teacher.rNotif = cNotif;

            return View("RemoveNotif", "_TeacherLayout", teacher);
        }

        /// <summary>
        /// Remove the notification from the database
        /// </summary>
        /// <param name="classID">ID of Class</param>
        /// <param name="notifID">ID of Notification</param>
        /// <returns>The Index page for the class</returns>
        public ActionResult RemoveNotification(int classID, int notifID)
        {
            
            if (test(classID) != null)
            {
                return test(classID);
            }
            List<HiddenNotification> HiddenNotifs = db.HiddenNotifications.Where(h => h.ClassNotificationID == notifID).ToList();
            ClassNotification notif = db.ClassNotifications.Where(n => n.ClassID == classID
                                                    && n.ClassNotificationID == notifID).FirstOrDefault();
            //remove any hidden notifications for this notifications
            foreach (HiddenNotification h in HiddenNotifs)
            {
                db.RemoveHiddenNotif(h);
            }
            db.SaveChanges();
            db.RemoveNotif(notif);
            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        /// <summary>
        /// Add Notification to the Database and to slack channel if available
        /// </summary>
        /// <param name="notif">text of notification</param>
        /// <param name="classID">ID of Class to add notification to</param>
        private void AddNotification(string notif, int classID)
        {

Oodle/Oodle/Views/Teachers/AddQuestion.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddQuestion</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Add a Question to Quiz: @Model.quiz.QuizName</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
            @Html.HiddenFor(Model => Model.question.QuizID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.question.Points, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.question.Points, new { htmlAttributes = new { @class = "form-control", min = 0, step = 1 } })
                    @Html.ValidationMessageFor(model => model.question.Points, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.question.QuestionText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.question.QuestionText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.question.QuestionText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.answer.Answer4, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer.Answer4, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.answer.Answer4, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(Model => Model.answer.QuestionID, new { @value = "-1" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.answer.CorrectAnswer, htmlAttributes: new { @class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.answer.CorrectAnswer, new { htmlAttributes = new { @class = "form-control", min = 1, max = 4, step = 1 } })
                    @Html.ValidationMessageFor(model => model.answer.CorrectAnswer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add Another Question" formaction=@Url.Action("AddAnother") formmethod="post" class="btn btn-default" />
                    <input type="submit" value="Finish" formaction=@Url.Action("SaveQuestion") formmethod="post" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to Quiz View", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, new { @class = "btn btn-default" })
    </div>
</body>
</html>

Oodle/Oodle/Views/Teachers/CreateAssignment.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "CreateAssignment";
}


<div class="form-style-6">
    <form method="post" action="CreateAssignmentAction" onsubmit="return compareTime()" name="formT">
        <div>
            <h1>Create an Assignment</h1>

            <label for="name">Name of Assignment:</label><br />
            <input type="text" name="name" placeholder="e.g., Assignment one, history of modernism" value="" required maxlength="128" /><br />
            <input type="hidden" name="classID" value="@Model.cl.ClassID" />

            <label for="description">Description of your Assignment:</label> <br />
            <textarea name="description" placeholder="e.g., please read chapter four and attach a word document of your answers to the questions at the end of the chapter." required maxlength="512"></textarea> <br />

            <label for="weight">Weight of Grade:</label> <br />
            <input type="number" name="weight" placeholder="0" value="" max="1000" min="0" required /><br />

            <br />
            <label for="startDate">Start Date</label><br />
            <input type="datetime-local" name="startDate" value="@DateTime.Now" required />

            <br />
            <label for="dueDate">Due Date</label><br />
            <input type="datetime-local" name="dueDate" value="@DateTime.Now" required min="@DateTime.Now.ToString("dd-mm-yyyyThh:mm:ss")" />
            <br />
            <label for="addNotif">Notify students of this assignment?</label>
            <input type="radio" name="addNotif" value="true">Yes
            <input type="radio" name="addNotif" value="false" checked>No <br />
        </div>
        <div>
            <input type="submit" name="submit" value="Create Assignment" />
        </div>
    </form>
</div>


<script>
    function compareTime() {
        var x = document.forms["formT"]["dueDate"].value;
        var y = document.forms["formT"]["startDate"].value;

        if (new Date(x) <= new Date(y)){
            alert("The due date must be after the start date.");
        }
        return new Date(x) > new Date(y); // true if time1 is later

    }
</script>






Oodle/Oodle/Views/Teachers/EditQuestion.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddQuestion</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Question for: @Model.quiz.QuizName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(Model => Model.question.QuizID)
        @Html.HiddenFor(Model => Model.question.QuestionID)
        @Html.HiddenFor(Model => Model.question.TypeOfQuestion)

        <div class="form-group">
            @Html.LabelFor(model => model.question.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question.Points, new { htmlAttributes = new { @class = "form-control", min = 0, step = 1 } })
                @Html.ValidationMessageFor(model => model.question.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question.QuestionText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.question.QuestionText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question.QuestionText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer.Answer1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.answer.Answer1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answer.Answer1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer.Answer2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.answer.Answer2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answer.Answer2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer.Answer3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.answer.Answer3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answer.Answer3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer.Answer4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.answer.Answer4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answer.Answer4, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(Model => Model.answer.AnswerID)
        @Html.HiddenFor(Model => Model.answer.QuestionID)

        <div class="form-group">
            @Html.LabelFor(model => model.answer.CorrectAnswer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answer.CorrectAnswer, new { htmlAttributes = new { @class = "form-control", min = 1, max = 4, step = 1 } })
                @Html.ValidationMessageFor(model => model.answer.CorrectAnswer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Edits" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to Quiz View", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, new { @class = "btn btn-default" })
    </div>
</body>
</html>

Oodle/Oodle/Views/Teachers/EditQuiz.cshtml
@model Oodle.Models.ViewModels.TeacherVM


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>Edit Quiz: @Model.quiz.QuizName</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.quiz.QuizID)
    <div class="form-group">
        @Html.LabelFor(model => model.quiz.QuizName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quiz.QuizName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quiz.QuizName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quiz.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quiz.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quiz.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quiz.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quiz.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quiz.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.quiz.ClassID)


    <div class="form-group">
        @Html.LabelFor(model => model.quiz.IsHidden, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.quiz.IsHidden)
                @Html.ValidationMessageFor(model => model.quiz.IsHidden, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quiz.CanReview, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.quiz.CanReview)
                @Html.ValidationMessageFor(model => model.quiz.CanReview, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    @Html.HiddenFor(model => model.quiz.TotalPoints)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit Edits" class="btn btn-default" />
        </div>
    </div>
</div>
}

    <div>
        @Html.ActionLink("Back to Quiz View", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, new { @class = "btn btn-default" })
    </div>

Oodle/Oodle/Views/Teachers/RemoveNotif.cshtml
@model Oodle.Models.ViewModels.TeacherVM


<div class="removeNotif">
    <h1>Remove Notification</h1>
    <p>Click the Remove Notification button to confirm removing, otherwise click the back button to go back to your class page</p>
    <p>Notification To Remove: @Model.rNotif.Notification</p>

    @Html.ActionLink("Back", "Index", "Teachers", new { ClassID = Model.rNotif.ClassID }, new { @class = "btn btn-default" })

    @Html.ActionLink("Remove Notification", "RemoveNotification", "Teachers", new { classID = Model.rNotif.ClassID, notifID = Model.rNotif.ClassNotificationID }, new { @class = "btn btn-default" })
    <p></p>

</div>

Oodle/Oodle/Views/Teachers/RemoveQuestion.cshtml
@model Oodle.Models.ViewModels.TeacherVM


<div class="removeNotif">
    <h1>Delete Question</h1>
    <p>Click the Delete Question button to confirm deleting the Question, otherwise click the back button to go back to the quiz page</p>
    <p>Question To Remove: @Model.question.QuestionText</p>

    @Html.ActionLink("Back To Quiz", "ViewQuiz", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID }, new { @class = "btn btn-default" })

    @Html.ActionLink("Delete Question", "DeleteQuizQuestion", "Teachers", new { QuizID = Model.quiz.QuizID, ClassID = Model.quiz.ClassID, QuestionID = Model.question.QuestionID }, new { @class = "btn btn-default" })
    <p></p>

</div>

Oodle/Oodle/Views/Teachers/SubmissionView.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "SubmissionView";
}

<h2>Submissions</h2>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
   
</head>
@using (Html.BeginForm("DownloadFile", "Students", FormMethod.Post))
{
    <input type="hidden" id="hfFileId" name="FileId" />
    <input type="submit" id="btnDownload" value="Download" style="display:none" />
}
<hr />
<table cellpadding="0" cellspacing="0" class="responsive-table">
    <tr>
        <th style="width:50px">Student</th>
        <th style="width:120px">File Name</th>
        <th style="width:120px">Grade Link</th>
        <th style="width:80px">Download</th>
    </tr>
    @if (Model.documents.Count() > 0)
    {
        for (int i = 0; i < Model.documents.Count(); i++)
        {
            var file = Model.documents[i];
            var user = Model.documents[i].UserID;
            string name = Model.users.Where(j => j.UsersID == user).FirstOrDefault().UserName;
            var classID = Model.cl.ClassID;
            var assignmentID = Model.assignment.FirstOrDefault().AssignmentID;
            <tr>
                <td>@name</td>
                <td>@file.Name</td>
                <td><a href="@Url.Action("Grade", "Teachers", new {classID = classID,documentID = file.Id,assignmentID = assignmentID})" style="color:dimgrey"> Grade </a></td>
                <td><a href="javascript:;" onclick="DownloadFile(@file.Id)" style="color:dimgrey">Download</a></td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="3">&nbsp;</td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    function DownloadFile(fileId) {
        $("#hfFileId").val(fileId);
        $("#btnDownload")[0].click();
    };
</script>